---

- name: Installation and Running Apache2 service
  hosts: all
  become: true

  tasks:
   - name: Installation of Apache2 Service
     apt:
       name: apache2
       state: present

   - name: Running the Apache2  Sevice on Target Server
     service:
       name: apache2
       state: started
       enabled: true
